// This file is being generated by an AI tool.
// It is not yet connected to a Firebase project.
import {initializeApp, getApps, getApp} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: 'TODO: Replace with your API key',
  authDomain: 'TODO: Replace with your auth domain',
  projectId: 'TODO: Replace with your project ID',
  storageBucket: 'TODO: Replace with your storage bucket',
  messagingSenderId: 'TODO: Replace with your messaging sender ID',
  appId: 'TODO: Replace with your app ID',
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export {app, auth, db};
